### PR TITLE
Bump `restic` to 0.17.2

### PR DESCRIPTION
**Pull request by apcamargo**
This PR updates `restic` to 0.17.2.

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by apcamargo** [comment]
@conda-forge-admin please rerender

**Comment by apcamargo** [comment]
@anjos @lsetiawan, can you take a look at this PR? I fixed the issue that prevented `restic` from being updated. and bumped it to the latest version.

**Review by lsetiawan — APPROVED** [review]
LGTM! Thank you for your contribution!

**Comment by apcamargo** [comment]
Thank you! Do we need to do something else before merging?

**Pull request merged**
